[package]
name = "sio2-derive"
version = "0.1.0"
edition = "2024"
description = "Proc macro derives for sio2"
license = "MIT"
repository = "https://github.com/baguettege/sio2"

[lib]
proc-macro = true

[features]
alloc = []

[dependencies]
proc-macro2 = "1.0.106"
syn = "2.0.117"
quote = "1.0.45"

[dev-dependencies]
sio2 = { workspace = true }
