[package]
name = "sio2-core"
version = "0.1.0"
edition = "2024"

[features]
alloc = []
std = ["alloc"]
indexmap = ["alloc", "dep:indexmap"]
hashbrown = ["alloc", "dep:hashbrown"]

[dependencies]
thiserror = { workspace = true }

indexmap = { workspace = true, optional = true }
hashbrown = { workspace = true, optional = true }
