[package]
name = "sio2-core"
version = "0.1.0"
edition = "2024"
description = "Core traits and types for sio2"
license = "MIT"
repository = "https://github.com/baguettege/sio2"

[features]
alloc = []
std = ["alloc"]
indexmap = ["alloc", "dep:indexmap"]
hashbrown = ["alloc", "dep:hashbrown"]

[dependencies]
thiserror = { workspace = true }

indexmap = { workspace = true, optional = true }
hashbrown = { workspace = true, optional = true }
