[package]
name = "sio2"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
alloc = [
    "sio2-core/alloc",
]
std = [
    "alloc",
    "sio2-core/std",
]
indexmap = ["alloc", "sio2-core/indexmap"]
hashbrown = ["alloc", "sio2-core/hashbrown"]

[dependencies]
sio2-core = { workspace = true }
